name: CS102 Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy sklearn nltk surprise pickle pandas
    - name: Run unittests
      run: |
        python -m unittest discover ${{ github.head_ref }}
